version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      WEBSOCKET_ENABLED: 'true'
      DOMAIN: "https://${VW_SUB}.${DOMAIN_ADDR}"
      LOG_LEVEL: warn
      SIGNUPS_ALLOWED: 'false'
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
    volumes:
      - vw-data:/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_net

      # HTTP to HTTPS redirect
      - traefik.http.routers.vaultwarden-http.entrypoints=http
      - traefik.http.routers.vaultwarden-http.rule=Host(`${VW_SUB}.${DOMAIN_ADDR}`)
      - traefik.http.routers.vaultwarden-http.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https

      # Main HTTPS route
      - traefik.http.routers.vaultwarden.entrypoints=https
      - traefik.http.routers.vaultwarden.rule=Host(`${VW_SUB}.${DOMAIN_ADDR}`)
      - traefik.http.routers.vaultwarden.tls=true
      - traefik.http.routers.vaultwarden.tls.certresolver=mycert
      - traefik.http.routers.vaultwarden.middlewares=secure@file,web-auth
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
    networks:
      - web_net

volumes:
  vw-data:

networks:
  web_net:
    external: true
